name: DMV Availability Notifier

on:
  push:
    branches: [master]  # or your branch
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}

concurrency:
  group: dmv-availability
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure jq is installed
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y jq | cat
          fi

      - name: Check DMV availability
        id: check
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          # Comma or space separated list, e.g. "33,19,29"
          LOCATION_IDS: ${{ vars.LOCATION_IDS }}
          TYPE_ID: ${{ vars.TYPE_ID }}
          BASE_URL: ${{ vars.BASE_URL }}
          START_DATE: ${{ vars.START_DATE }}
          LOCATION_NAME_MAP: ${{ vars.LOCATION_NAME_MAP }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_FORMAT: ${{ vars.WEBHOOK_FORMAT }}
          WEBHOOK_JSON_KEY: ${{ vars.WEBHOOK_JSON_KEY }}
        run: |
          bash scripts/check_availability.sh
          echo "found=$(cat .availability/found)" >> "$GITHUB_OUTPUT"
          {
            echo "summary<<EOF"
            cat .availability/summary.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Send Discord webhook
        if: steps.check.outputs.found == 'true'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ -z "${DISCORD_WEBHOOK_URL}" ]; then
            echo "DISCORD_WEBHOOK_URL not set; skipping"
            exit 0
          fi
          # Discord limit is 2000 characters; trim to be safe
          msg=$(cat .availability/summary.txt | head -c 1900)
          jq -Rn --arg content "$msg" '{content: $content}' > payload.json
          echo "Posting to Discord webhook..."
          http_code=$(curl -sS -D headers.txt -o body.txt -w "%{http_code}" \
            -H "Content-Type: application/json" -d @payload.json "$DISCORD_WEBHOOK_URL")
          echo "--- Response status: ${http_code}"
          echo "--- Response headers:"
          cat headers.txt || true
          echo "--- Response body:"
          cat body.txt || true

      # Email notification removed per request; webhook notification remains in the script


